services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.environment/local/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./:/app/
  php:
    build: ./.environment/local/php
    environment:
      PHP_IDE_CONFIG: "serverName=chat"
    volumes:
      - ./:/app
      - ./.environment/local/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /tmp/xdebug:/tmp/xdebug

  db:
    image: postgres:14-alpine3.17
    restart: always
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local